function  caracteristici(r,l)
Fig=figure('Name','Caract. de frecventa ale filtrului RL Trece Jos',...
           'Units','normalized',...
           'Position',[0.05, 0.01, 0.8, 0.9],...
           'color',[0.93 0.91 0.8],...
           'NumberTitle','off');
       
   uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.01 0.920 0.36 0.08],...
        'backgroundcolor',[0.93 0.91 0.8],...',...
        'foregroundcolor',[0 0 0],...
        'Fontname','Arial Black',...
        'FontWeight','Bold',...
        'FontSize',15,...
        'String','Caracteristicile de frecventa ale FTJ');
r1=r*10.^3;% kilo ohmi
l1=l*10.^-6; %micro Henry
f0=r1/(2*pi*l1); %frecventa de taiere
w=logspace(1,6,100);
f=w/(2*pi);%frecventa
num=1; %numaratorul functiei de transfer
 den=j*w*l1/r1 + 1;%numitorul functiei de transfer
h=abs(num./den); %modulul functiei de transfer
gain=20*log10(h); %logaritmul zecimal al functiei de transfer
phase=angle(num./den)*180/pi;%faza in grade


%Caracteristica modul-frecventa 

subplot('Position', [0.1 0.7 0.4 0.1]);
 semilogx(f,gain,'r');grid on;
title('Caracteristicile de frecventa ale filtrului RL trece jos');
xlabel('Frecventa[Hz]');ylabel('Castigul [dB]');
uicontrol('style','Text',...
          'Units','normalized',...
          'Position',[0.2 0.82 0.1 0.04],...
          'Backgroundcolor',[0.93 0.91 0.8],...
         'string','Castigul',...
          'FontName','Arial Black',...
          'FontSize',10,...
          'Callback','close;');

%  Caracteristica faza-frecventa 

 subplot('Position', [0.1 0.5 0.4 0.1]);
semilogx(f,phase,'b');
grid on;
xlabel('Frecventa[Hz]');ylabel('Faza');
uicontrol('style','Text',...
          'Units','normalized',...
          'Position',[0.2 0.6 0.1 0.04],...
         'string','Faza',...
          'FontName','Arial Black',...
          'FontSize',10,...
         'BackgroundColor',[0.93 0.91 0.8],...
          'Callback','close;');
      
 uicontrol('style','Text',...
          'Units','normalized',...
          'Position',[0.845 0.82 0.15 0.07],...
          'BackgroundColor',[194/255, 199/255, 145/255],...
         'string','R[KΩ]',...
          'FontName','Arial Black',...
          'FontSize',10);
edit_r=uicontrol('style','Edit',...
          'Units','normalized',...
          'Position',[0.845 0.76 0.15 0.07],...
           'FontName','Arial Black',...
          'FontSize',12,...
          'ForegroundColor',[0 0 0],...
          'BackgroundColor',[1 1 1],...
          'string',r,...
          'Callback','r=str2num(get(gco,''String'')),caracteristici(r,l)');
       
%Modificarea valorii inductantei     

uicontrol('style','Text',...
          'Units','normalized',...
          'Position',[0.845 0.65 0.15 0.07],...
         'string','L [ μH]',...
          'FontName','Arial Black',...
          'FontSize',12,...
          'BackgroundColor',[194/255, 199/255, 145/255]);
      
edit_l=uicontrol('style','Edit',...
          'Units','normalized',...
          'Position',[0.845 0.58 0.15 0.07],...
           'FontName','Arial Black',...
          'FontSize',12,...
          'ForegroundColor',[0 0 0],...
          'BackgroundColor',[1 1 1],...
          'string',l,...
          'Callback','l=str2num(get(gco,''String'')),r,caracteristici(r,l)');
     
      
% Crearea butoanelor


      
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.845 0.15 0.15 0.1],...
          'string','Inchide',...
          'FontName','Arial Black',...
          'FontSize',12,...
          'BackgroundColor',[194/255, 199/255, 145/255],...
          'Callback','close;');
 Group=uibuttongroup('Visible','on',...
                     'BackgroundColor',[0.75,0.75,0.5],...
                     'ForegroundColor','black',...
                     'Title','Formule',...
                     'FontSize',12,...
                     'TitlePosition','centertop',...
                     'Tag','button',...
                     'BackgroundColor',[194/255, 199/255, 145/255],...
                     'Position',[0.05 0.2 0.5 0.25]);
        Br=uicontrol('Style','pushbutton',...
                     'Units','normalized',...
                     'BackgroundColor',[194/255, 199/255, 145/255],...
                     'Fontname','Arial Black',...
                     'position',[0.03 0.55 0.6 0.5],...
                     'String','Functia de transfer',...
                     'Parent',Group,...
                     'Callback','ft();');
        Br=uicontrol('Style','pushbutton',...
                     'Units','normalized',...
                     'BackgroundColor',[194/255, 199/255, 145/255],...
                     'Fontname','Arial Black',...
                     'position',[0.03 0.01 0.6 0.5],...
                     'String','Tensiunea de iesire',...
                     'Parent',Group,...
                     'Callback','vo();');
 Group2=uibuttongroup('Visible','on',...
                      'BackgroundColor',[194/255, 199/255, 145/255],...
                      'ForegroundColor','black',...
                      'Title','Calcule',...
                      'FontSize',15,...
                      'Position',[0.05 0.02 0.5 0.15],...
                      'FontWeight','Bold',...
                      'Fontname','Comic Sans MS',...
                      'TitlePosition','centertop',...
                      'Tag','radiobutton');
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.1 0.025 0.86 0.7],...
        'BackgroundColor',[194/255, 199/255, 145/255],...
        'foregroundcolor','black',...
        'FontWeight','Bold',...
        'FontSize',15,...
        'String',['Fo[Hz] = ',num2str(f0)],...
        'Parent',Group2);
end

