function  caracteristiciRC(R,C,P)
Fig=figure('Name','Caracteristici de frecventa ale filtrului RL Trece Jos',...
           'Units','normalized',...
           'Position',[0.1 0.2 0.8 0.7],...
           'color',[0.93 0.91 0.8],...
           'NumberTitle','off');
%Titlu
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.3 0.920 0.36 0.08],...
        'backgroundcolor',[0.93 0.91 0.8],...
        'foregroundcolor',[0 0 0],...
        'Fontname','Arial Black',...
        'FontWeight','Bold',...
        'FontSize',12,...
        'String','Caracteristicile de frecventa ale FTJ');
    
   

%Initializare marimi specifice filtrului
r1=R*10.^3;                    % kilo ohmi
 c1=C*10.^-6;                   %microfarazi
 w=logspace(-1,8, P); %nr de pct f distribuite logaritmic
  f0=1./(2.*pi.*r1.*c1);
  w0=2.*pi.*f0;
  f=w/(2*pi); 
 numarator=1;
 numitor=1 + j*w*r1*c1;
 H=abs(numarator./numitor); 
 Castig=20*log10(H);
 faza=angle(numarator./numitor)*180./pi;%angle afiseaza unghiul in radiani,deci l am convertit in grade
 

% Reprezentare faza
 subplot('Position', [0.1 0.35 0.4 0.18]);
 semilogx(f,faza,'m-',f0,-45,'d','LineWidth',1);
 xlabel('Frecventa [ Hz ]');
 ylabel('Faza [ grade ]');
 title('Faza semnalului',...
       'Fontweight','b','Color','black');
 legend('Faza');
 grid on;

%Reprezentare Castig
 subplot('Position', [0.1 0.65 0.4 0.18]);
 semilogx(f,Castig,'g-',f0,-3,'d','LineWidth',1);
 xlabel('Frecventa [ Hz ]');
 ylabel('Castigul [ dB ]');
 title('Castigul','fontweight','b','Color','black');
 legend('Castigul');
 grid on;
 



Group1=uibuttongroup('Visible','on',...
        'BackgroundColor',[194/255, 199/255, 145/255],...
        'ForegroundColor','black',...
        'Title','Valori si Parametrii',...
        'FontSize',20,...
        'Position',[0.6 0.21 0.3 0.72],...
        'FontWeight','Bold',...
        'TitlePosition','centertop',...
        'Fontname','Comic Sans MS',...
        'Tag','radiobutton');
% Grup de butoane parametrii circuitului
Group2=uibuttongroup('Visible','on',...
       'BackgroundColor',[194/255, 199/255, 145/255],...
        'ForegroundColor','black',...
        'Title','Valori numerice',...
        'FontSize',13,...
        'Position',[0.11 0.42 0.8 0.55],...
        'FontWeight','Bold',...
        'Fontname','Arial Black',...
        'TitlePosition','centertop',...
        'Parent',Group1,...
        'Tag','radiobutton');
%Valoare rezistenta
rt=uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.19 0.750 0.4 0.23],...
        'BackgroundColor',[194/255, 199/255, 145/255],....
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','R[KΩ]',...
        'FontWeight','Bold',...
        'Parent',Group2);
re=uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.65 0.75 0.3 0.23],...
        'FontSize',15,...
        'BackgroundColor',[194/255, 199/255, 145/255],...
        'String', R,...
        'FontWeight','Bold',...
        'Parent',Group2,...
        'Callback','R=str2num(get(gco,''String'')),caracteristiciRC(R,C,P)');
%Valoare capacitate
ct=uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.19 0.45 0.45 0.23],...
       'BackgroundColor',[194/255, 199/255, 145/255],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'FontWeight','Bold',...
        'String','C[ μF]',...
        'Parent',Group2);
ce=uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.65 0.45 0.3 0.23],...
        'FontSize',15,...
        'BackgroundColor',[194/255, 199/255, 145/255],...
        'String', C,...
        'FontWeight','Bold',...
        'Parent',Group2,...
        'Callback','C=str2num(get(gco,''String'')),caracteristiciRC(R,C,P)');
    Group3=uibuttongroup('Visible','on',...
        'BackgroundColor',[194/255, 199/255, 145/255],...
        'ForegroundColor','black',...
        'Title','Formule',...
        'FontSize',20,...
        'Position',[0.55 0.01 0.4 0.2],...
        'FontWeight','Bold',...
        'TitlePosition','centertop',...
        'Fontname','Arial Black',...
        'Tag','radiobutton');
     Br=uicontrol('Style','pushbutton',...
                   'Units','normalized',...
                   'BackgroundColor',[194/255, 199/255, 145/255],...
                   'Fontname','Arial Black',...
                   'position',[0.03 0.55 0.6 0.5],...
                   'String','Functia de transfer',...
                   'Parent',Group3,...
                   'Callback','frRC()');
                       
         
%Valoare precizie
    pt=uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.19 0.15 0.4 0.23],...
        'foregroundcolor','black',...
        'FontSize',15,...
         'BackgroundColor',[194/255, 199/255, 145/255],...
        'FontWeight','Bold',...
        'String','Precizie',...
        'Parent',Group2);
pe=uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.65 0.15 0.3 0.23],...
        'FontSize',15,...
        'String', P,...
        'BackgroundColor',[194/255, 199/255, 145/255],...
        'FontWeight','Bold',...
        'Parent',Group2,...
        'Callback','P=str2num(get(gco,''String'')),close,caracteristiciRC(R,C,P)');
    
% Calcul frecventa de taiere       
Group4=uibuttongroup('Visible','on',...
        'BackgroundColor',[194/255, 199/255, 145/255],...
        'ForegroundColor','black',...
        'Title','Frecventa de taiere',...
        'FontSize',12,...
        'Position',[0.1 0.1 0.8 0.30],...
        'FontWeight','Bold',...
        'Fontname','Arial Black',...
        'TitlePosition','centertop',...
        'Parent',Group1,...
        'Tag','radiobutton');
uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.1 0.025 0.86 0.7],...
        'BackgroundColor',[194/255, 199/255, 145/255],...
        'foregroundcolor','black',...
        'FontWeight','Bold',...
        'FontSize',15,...
        'String',['Fo[Hz] = ',num2str(f0)],...
        'Parent',Group4);

 end

