clear all;

%definirea variabilelor
R=1;
C=1;
P=100;
sel=1;

%crearea figurii
Fig = figure('Name', 'Filtru trece jos RC',...
             'NumberTitle', 'off', ...
             'Color', [240/255, 243/255, 207/255],...
             'Position', [50, 50, 1000, 600]);
Bt=uicontrol('Style','text',...
             'Units','normalized',...
             'Position',[0.2 0.93 0.6 0.07],...
             'Fontsize',16,...
             'FontName','Arial Black',...
             'String','Filtru trece jos RC',...
             'Backgroundcolor',[240/255, 243/255, 207/255]);
       
subplot(1,2,1)     
w=imread('ftj_rc.jpg');
imshow(w);
 uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.7 0.6 0.205 0.1],...
           'BackgroundColor',[194/255, 199/255, 145/255],...
          'string','Caracteristici',...
          'FontName','Arial Black',...
          'FontSize',12,... 
          'Callback','caracteristiciRC(R,C,P);');
      uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.7 0.8 0.205 0.1],...
           'BackgroundColor',[194/255, 199/255, 145/255],...
          'string','Notiuni generale teoretice',...
          'FontName','Arial Black',...
          'FontSize',12,... 
          'Callback','open (''FTJ_RC.pdf'')');
%buton iesire
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.7 0.2 0.205 0.1],...
          'BackgroundColor',[206/255, 51/255, 19/255],...
          'string','Iesire',...
          'FontName','Arial Black',...
          'FontSize',12,...          
          'Callback','close;');
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.7 0.4 0.205 0.1],...
          'BackgroundColor',[194/255, 199/255, 145/255],...
          'string','Functionalitate',...
          'FontName','Arial Black',...
          'FontSize',12,...          
          'Callback','functionalitate(R,C)');