function functionalitateRL(R,L)
Fig=figure('Name','Functionalitatea filtrului RL Trece Jos',...
           'Units','normalized',...
           'Position',[0.1 0.2 0.8 0.7],...
           'color',[0.93 0.91 0.8],...
           'NumberTitle','off');
 rt=uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.1 0.1 0.15 0.07],...
        'BackgroundColor',[194/255, 199/255, 145/255],....
        'foregroundcolor','black',...
        'FontSize',15,...
        'String','R[Ohm]',...
        'FontWeight','Bold');
re=uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.1 0.05 0.15 0.07],...
        'FontSize',15,...
        'BackgroundColor',[194/255, 199/255, 145/255],...
        'String', R,...
        'FontWeight','Bold',...
        'Callback','R=str2num(get(gco,''String'')),functionalitateRL(R,L)');
% Valoare L
ct=uicontrol('Style','text',... 
        'Units','normalized',...
        'Position',[0.3 0.1 0.15 0.07],...
       'BackgroundColor',[194/255, 199/255, 145/255],...
        'foregroundcolor','black',...
        'FontSize',15,...
        'FontWeight','Bold',...
        'String','L[Henri]');
ce=uicontrol('Style','edit',...
        'Units','normalized',...
        'Position',[0.3 0.05 0.15 0.07],...
        'FontSize',15,...
        'BackgroundColor',[194/255, 199/255, 145/255],...
        'String', L,...
        'FontWeight','Bold',...
        'Callback','L=str2num(get(gco,''String'')),functionalitateRL(R,L)');
fs = 1000;    %f de esantionare ,numarul de masuratori/s, Hz
dur_sec = 1;   % Durata semnalului, secunde
t_sec = (0:(dur_sec*fs)-1)/fs;  % Vectorul de timp
freq_Hz = 20;  % Frecvența semnalului, Hz
y = sin(2*pi*freq_Hz*t_sec);  % Generarea semnalului
N = 1;  % Ordinul filtrului
f0 = R/(2*pi*L);  % Frecvența de tăiere, Hz
% Calcularea coeficienților filtrului trece-jos
wc = 2 * pi * f0 / fs;  % Frecvența de tăiere normalizată
a = [1, -exp(-wc)];  % Coeficienții din numitor
b = (1 - exp(-wc)) * [1, 1];  % Coeficienții din numărător

% Aplicare filtru
y_filt = filter(b, a, y);

% Afișare rezultate

subplot(2,1,1)
plot(t_sec, y, t_sec, y_filt);
xlabel('Timp (secunde)');
ylabel('Amplitudine');
% ylim([-1 1]);
legend('Semnal brut', 'Semnal filtrat');
title('Filtru trece-jos Rl');
