clear all;

%definirea variabilelor
R=1;
L=1;
r=1;
l=1;
%Crearea figurii 
Fig = figure('Name', 'Filtru trece jos RL',...
             'NumberTitle', 'off', ...
             'Color', [240/255, 243/255, 207/255],...
             'Position', [50, 50, 1000, 600]);
Bt=uicontrol('Style','text',...
             'Units','normalized',...
             'Position',[0.36 0.93 0.3 0.04],...
             'Fontsize',16,...
             'FontName','Arial Black',...
             'String','Filtru RL trece jos',...
             'Backgroundcolo',[240/255, 243/255, 207/255]);
       
subplot(1,2,1)     
w=imread('RL.jpg');
imshow(w);
      uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.7 0.8 0.205 0.1],...
           'BackgroundColor',[194/255, 199/255, 145/255],...
          'string','Functionalitate',...
          'FontName','Arial Black',...
          'FontSize',12,... 
          'Callback','functionalitateRL(R,L);');
%buton pentru grafice
      uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.7 0.6 0.205 0.1],...
           'BackgroundColor',[194/255, 199/255, 145/255],...
          'string','Caracteristici',...
          'FontName','Arial Black',...
          'FontSize',12,... 
          'Callback','caracteristici(r,l);');
%buton iesire
uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.7 0.2 0.205 0.1],...
          'BackgroundColor',[206/255, 51/255, 19/255],...
          'string','Iesire',...
          'FontName','Arial Black',...
          'FontSize',12,...          
          'Callback','close;');
      %buton prezentare pdf
 uicontrol('style','pushbutton',...
          'Units','normalized',...
          'Position',[0.7 0.4 0.205 0.1],...
          'BackgroundColor',[194/255, 199/255, 145/255],...
          'string','Notiuni generale teoretice',...
          'FontName','Arial Black',...
          'FontSize',12,...          
          'Callback','open (''FTJ_RL.pdf'')');