Fig = figure('Name', 'Filtru trece jos ',...
             'NumberTitle', 'off', ...
             'Color', [94/255, 171/255, 130/ 255],...
             'Position', [50, 50, 1000, 600]);
      Bt=uicontrol('Style','text',...
                    'Units','normalized',...
                    'Position',[0.36 0.9 0.3 0.07],...
                    'Fontsize',20,...
                    'FontName','Arial Black',...
                    'String','Proiect GAC',...
                    'Backgroundcolo',[94/255, 171/255, 130/ 255]);
      Group=uibuttongroup('Visible','on',...
                     'BackgroundColor',[0.75,0.75,0.5],...
                     'ForegroundColor','black',...
                     'Title','Circuite',...
                     'FontSize',12,...
                     'TitlePosition','centertop',...
                     'Tag','button',...
                     'BackgroundColor',[181/255, 173/255, 105/255],...
                     'Position',[0.25 0.4 0.5 0.4]);
        Br=uicontrol('Style','pushbutton',...
                       'Units','normalized',...
                       'BackgroundColor',[194/255, 199/255, 145/255],...
                       'Fontname','Arial Black',...
                       'position',[0.03 0.55 0.8 0.5],...
                       'String','Filtru trece jos RL',...
                       'Parent',Group,...
                       'Callback','interfataftjRL();');
          Br=uicontrol('Style','pushbutton',...
                       'Units','normalized',...
                       'BackgroundColor',[194/255, 199/255, 145/255],...
                       'Fontname','Arial Black',...
                       'position',[0.03 0.01 0.8 0.5],...
                       'String','Filtru trece jos RC',...
                       'Parent',Group,...
                       'Callback','filtrutrecejosRC');  
                   Br=uicontrol('Style','pushbutton',...
                       'Units','normalized',...
                       'BackgroundColor','r',...
                       'Fontname','Arial Black',...
                       'position',[0.8 0.01 0.2 0.1],...
                       'String','Iesire',...
                       'Callback','close');  
           f=uimenu('Label','Meniu proiect');
           uimenu(f,'Label','Autor','Callback','open (''Autor.pdf'')');
           uimenu(f,'Label','Documentatie','Callback','open (''Documentatie.pdf'')');
           uimenu(f,'Label','Teorie FTJ RL','Callback','open (''FTJ_RL.pdf'')');
           uimenu(f,'Label','Teorie FTJ RC','Callback','open (''FTJ_RC.pdf'')');
             uimenu(f,'Label','Bibliografie','Callback','open (''Bibliografie.pdf'')');
           uimenu(f,'Label','Iesire','Callback','close',...
                 'Separator','on','Accelerator','Q');